//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.DataEntitiess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime ArticleDate { get; set; }
        public string Author { get; set; }
        public string ArticleImage { get; set; }
        public Nullable<int> ArticleViews { get; set; }
        public bool Is_Active { get; set; }
    }
}
