//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.DataEntitiess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        public int ID { get; set; }
        public string Comment { get; set; }
        public string CommentByName { get; set; }
        public string EPOSTA { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<int> USTID { get; set; }
        public Nullable<int> MAKALEID { get; set; }
        public Nullable<bool> Is_Approve { get; set; }
    }
}
