//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.DataEntitiess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILLS
    {
        public int ID { get; set; }
        public string SKILLYUZDE { get; set; }
        public string SKILLTITLE { get; set; }
        public string SKILL_TITLE_BG { get; set; }
        public string SKILL_BAR_BG { get; set; }
    }
}
